# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: mongodb
    image: mongo
    # restart: always
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /home/anton/Documents/mongodb_data:/data/db
    ports:
      - 27017:27017

  mongo-express:
    container_name: mongodb_express
    image: mongo-express
    # restart: always
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
